const selectors = {
  pantalla1: {
    clickSiguiente:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.ThHDze > div.DE3NNc.CekdCb > div.lRwqcd > div > span",
  },
  pantalla2: {
    femenino:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.oyXaNc > div > div > span > div > div:nth-child(1) > label > div > div.YEVVod > div > span",
    masculino:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.oyXaNc > div > div > span > div > div:nth-child(2) > label > div > div.YEVVod > div > span",
    edad: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.AgroKb > div > div.aCsJod.oJeWuf > div > div.Xb9hP > input",
    distrito:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.AgroKb > div > div.aCsJod.oJeWuf > div > div.Xb9hP > input",
    clickSiguiente:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.ThHDze > div.DE3NNc.CekdCb > div.lRwqcd > div:nth-child(2) > span",
  },
  pantalla3: {
    accedoAParticipar: "#i5 > div.vd3tt > div",
    clickSiguiente:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.ThHDze > div.DE3NNc.CekdCb > div.lRwqcd > div:nth-child(2) > span",
  },
  pantalla4: {
    pregunta1: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta2: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta3: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta4: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta5: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta6: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta7: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta8: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta9: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta10: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta11: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta12: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta13: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta14: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta15: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta16: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta17: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta18: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta19: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta20: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta21: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta22: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta23: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta24: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta25: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
      o5: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(6) > div.eRqjfd > div > div > div.vd3tt > div",
      o6: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(7) > div.eRqjfd > div > div > div.vd3tt > div",
      o7: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(8) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    clickSiguiente:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.ThHDze > div.DE3NNc.CekdCb > div.lRwqcd > div:nth-child(2) > span",
  },
  pantalla5: {
    pregunta1: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(2) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta2: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(3) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta3: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(4) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta4: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(5) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta5: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(6) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta6: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(7) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta7: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(8) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta8: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(9) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta9: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(10) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta10: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(11) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta11: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(12) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta12: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(13) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta13: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(14) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta14: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(15) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta15: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(16) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta16: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(17) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta17: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(18) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta18: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(19) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta19: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(20) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta20: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(21) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta21: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(22) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta22: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(23) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta23: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(24) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta24: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(25) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta25: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(26) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta26: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(27) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(27) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(27) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(27) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta27: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(28) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(28) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(28) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(28) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta28: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(29) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(29) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(29) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(29) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta29: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(30) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(30) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(30) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(30) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta30: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(31) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(31) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(31) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(31) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta31: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(32) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(32) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(32) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(32) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta32: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(33) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(33) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(33) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(33) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta33: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(34) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(34) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(34) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(34) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta34: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(35) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(35) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(35) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(35) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta35: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(36) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(36) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(36) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(36) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta36: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(37) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(37) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(37) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(37) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta37: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(38) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(38) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(38) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(38) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta38: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(39) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(39) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(39) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(39) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta39: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(40) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(40) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(40) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(40) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta40: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(41) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(41) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(41) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(41) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta41: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(42) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(42) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(42) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(42) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta42: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(43) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(43) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(43) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(43) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta43: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(44) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(44) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(44) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(44) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    pregunta44: {
      o1: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(45) > div > div > div.PY6Xd > div > span > div > label:nth-child(2) > div.eRqjfd > div > div > div.vd3tt > div",
      o2: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(45) > div > div > div.PY6Xd > div > span > div > label:nth-child(3) > div.eRqjfd > div > div > div.vd3tt > div",
      o3: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(45) > div > div > div.PY6Xd > div > span > div > label:nth-child(4) > div.eRqjfd > div > div > div.vd3tt > div",
      o4: "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.o3Dpx > div:nth-child(45) > div > div > div.PY6Xd > div > span > div > label:nth-child(5) > div.eRqjfd > div > div > div.vd3tt > div",
    },
    enviarForm:
      "#mG61Hd > div.RH5hzf.RLS9Fe > div > div.ThHDze > div.DE3NNc.CekdCb > div.lRwqcd > div.uArJ5e.UQuaGc.Y5sE8d.VkkpIf.QvWxOd > span",
  },
};

module.exports = selectors;
